### ISSUE TITLE
dapp crashes for big number buy amount

### ISSUE THREAD

**Issue by acrdlph** [convergentcx/Arena#52]
Unhandled Rejection (Error): while converting number to string, invalid number value '', should be a number matching (^-?[0-9.]+).
▶ 3 stack frames were collapsed.
addDecimals
src/util/index.js:7
   4 | const { toBN } = w3utils;
   5 | 
   6 | export const addDecimals = tokens => {
  7 |   return w3utils.toWei(String(tokens), 'ether').toString();
   8 | };
   9 | 
  10 | export const getPrice = (inverseSlope, supply, exp) => {

**Comment by lsaether** [comment]
` invalid number value ''` leads me to believe that an empty string was being passed in as input, please try to re-create this bug and specify which exact inputs will trigger the error again. Otherwise, I will look into this in the evening.

**Comment by acrdlph** [comment]
i checked again with the most recent master and i still get this bug, but i realized its not because of big numbers. it always happens when i enter a number in the buy or sell field under the bonding curve chart and then delete it.

**Comment by lsaether** [comment]
completed
