### ISSUE TITLE
bug when image is missing

### ISSUE THREAD

**Issue by acrdlph** [convergentcx/Arena#53]
Unhandled Rejection (TypeError): First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
▼ 3 stack frames were expanded.
fromObject
node_modules/buffer/index.js:326
from
node_modules/buffer/index.js:142
Function.push../node_modules/buffer/index.js.Buffer.from
node_modules/buffer/index.js:155
▲ 3 stack frames were expanded.
ProfileCard._callee$
src/components/Dashboard/MyToken/ProfileCard/index.jsx:21
  18 | 
  19 | async componentDidMount() {
  20 |   const { image } = this.props.jsonData;
  21 |   const pic = Buffer.from(image.data).toString('base64');
     | ^  22 |   this.setState({ pic });
  23 | }
  24 |

**Comment by lsaether** [comment]
I believe this is fixed in latest master branch but if not this is the code block that should work:
```
    let pic = '';
    if (image.data) {
      pic = Buffer.from(image.data).toString('base64');
    }
```
