### ISSUE TITLE
Fix the router history to be able to Refresh pages /  navigate to URLs by typing them

### ISSUE THREAD

**Issue by lsaether** [convergentcx/Arena#75]
Issue: When a user tries to navigate to a previous page from a page in the DApp, the page returns 404 if it doesn't land on the base URL (right now found at `https://proto.convergent.cx`).

Fix: Change the router config to allow for navigation of the history. This may mean changing the router to a `HashRouter` or it may be resolved in some other way. Not super familiar on React Router myself so requires some quick research for the right solution.

**Comment by lsaether** [comment]
@acrdlph did you push a fix to this? I cannot reproduce this now on the latest live version of the DApp.

**Comment by acrdlph** [comment]
@lsaether did not fix this, but the error persists for me using firefox on your lenovo!

**Comment by lsaether** [comment]
Quick fix would be to use Hash router

https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writting-manually
